site_name: Marco A Almeida
site_url: https://marcoaalmeida.github.io/

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: deep orange
    accent: pink
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
